// Svelte-Complete-Guide/06_components-deep-dive/src/Modal.svelte
<script>
    import { createEventDispatcher, onMount, onDestroy, beforeUpdate, afterUpdate } from 'svelte';

    const dispatch = createEventDispatcher();

    let agreed = false;
    let autoscroll = false;

    // lifecycle hooks:
    onMount(() => {
        console.log('onMount()');
    });
    onDestroy(() => {
        console.log('onDestroy()');
    });

    beforeUpdate(() => {
        console.log('beforeUpdate()');
        autoscroll = agreed;
    });

    afterUpdate(() => {
        console.log('afterUpdate()');
        if (autoscroll) {
            const modal = document.querySelector('.modal');
            modal.scrollTo(0, modal.scrollHeight);
        }
    });

    console.log('Script executed');
</script>

<style>
    .backdrop {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100vh;
        background: rgba(0, 0, 0, 0.75);
        z-index: 10;
    }

    .modal {
        padding: 1rem;
        position: fixed;
        top: 10vh;
        left: 10%;
        width: 80%;
        max-height: 15vh;
        background: white;
        border-radius: 5px;
        z-index: 100;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.26);
        overflow: auto;
    }

    header, main {
        border-bottom: 1px solid #ccc;
    }
</style>

<div class="backdrop" on:click="{() => {dispatch('cancel')}}"></div>
<div class="modal">
    <header>
        <slot name="header"/>
    </header>
    <main>
        <slot name="content"/>
    </main>
    <div class="disclaimer">
        <p>Before you close you need to agree to our terms</p>
        <button on:click="{() => {agreed = true}}">Agree</button>
    </div>
    <footer>
        <slot name="footer" didAgree={agreed}> <!-- didAgree is a slop prop that can be passed from parent -->

            <!-- default content if nothing is passed to "footer" slot -->
            <button 
                on:click="{() => {dispatch('close')}}"
                disabled="{!agreed}">
                Close
            </button>
        </slot>
    </footer>
</div>

// Web-Components-StencilJS/05_More-complex-components/modal.js
class Modal extends HTMLElement {
    constructor() {
        super();
        this.attachShadow({mode: 'open'});
        this.shadowRoot.innerHTML = `
            <style>
                #backdrop {
                    position: fixed;
                    top: 0;
                    left: 0;
                    width: 100vw;
                    height: 100vh;
                    background-color: rgba(0,0,0,0.75);
                    z-index: 10;
                    opacity: 0;
                    pointer-events: none;
                    transition: all .2s ease;
                }
                #modal {
                    position: fixed;
                    top: 15vh;
                    left: 30%;
                    width: 40%;
                    z-index: 100;
                    background: white;
                    border-radius: 3px;
                    box-shadow: 0 2px 8px rgba(0,0,0,0.26);
                    display: flex;
                    flex-direction: column;
                    justify-content: space-between;
                    opacity: 0;
                    pointer-events: none;
                    transform: translateY(-30%);
                    transition: all .2s ease;
                }
                :host([opened]) #backdrop,
                :host([opened]) #modal {
                    opacity: 1;
                    pointer-events: all;
                }
                :host([opened]) #modal {
                    transform: translateY(0);
                }
                header {
                    padding: 1rem;
                }
                ::slotted(h1) {
                    font-size: 1.25rem;
                    margin-bottom: 0;
                }
                main {
                    padding: 1rem;
                    margin-bottom: 1rem;
                }
                #actions {
                    border-top: 1px solid #ccc;
                    padding: 1rem;
                    display: flex;
                    justify-content: flex-end;
                }
                #actions button {
                    margin: 0 0.25rem;
                    background: none;
                }

            </style>
            <div id="backdrop"></div>
            <div id="modal">
                <header>
                    <slot name="title">Default Title</slot>                    
                </header>
                <main>
                    <slot></slot>
                </main>
                <footer id="actions">
                    <button>Cancel</button>
                    <button>Okay</button>
                </footer>
            </div>
        `;
        // const slots = this.shadowRoot.querySelectorAll('slot');
        // slots[1].addEventListener('slotchange', (event) => {
        //     console.dir(slots[1].assignedNodes());
        // });
    }

    connectedCallback() {
        const cancelButton = this.shadowRoot.querySelector('button:first-child');
        const confirmButton = this.shadowRoot.querySelector('button:last-child');
        
        cancelButton.addEventListener('click', () => {
            this.dispatchEvent(new Event('cancel'));
            this.close();
        });
        confirmButton.addEventListener('click', () => {
            this.dispatchEvent(new Event('confirm'));
            this.close();
        });
        this.shadowRoot.querySelector('#backdrop').addEventListener('click', () => {
            this.close();
        });
    }

    open() {
        this.setAttribute('opened', '');
    }
    close() {
        this.removeAttribute('opened');
    }
}

customElements.define('pk-modal', Modal);
